---
# vars file for zabbix

packages_1:
  - mysql-server
  - nginx
  - php8.1-fpm
  - xz-utils
  - python3-pymysql
  - acl
  - unzip
  - tar

packages_2:
  - zabbix-server-mysql
  - zabbix-frontend-php
  - zabbix-nginx-conf
  - zabbix-sql-scripts
  - zabbix-agent

zabbix_db_name: 'zabbix'
zabbix_db_user: 'zabbix'
zabbix_db_password: 'zabbix_mysql_pass'
