---
# tasks file for db_host 

- name: Выполнить apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Установить пакеты
  ansible.builtin.apt:    
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Создать пользователя "{{ db_user }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE

- name: Создать пользователя "{{ replica_user }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ replica_user }}"
    password: "{{ replica_password }}"
    role_attr_flags: REPLICATION

- name: Загружаем дамп БД на сервер БД
  ansible.builtin.copy:
    src: files/my_wiki.sql
    dest: /tmp/my_wiki.sql

- name: Создать базу "{{ db_name }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    state: present 

- name: Заполнить базу "{{ db_name }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    state: restore
    target: /tmp/my_wiki.sql

- name: Настроить доступ для хостов MediaWiki
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: host
    databases: "{{ db_name }}"
    users: "{{ db_user }}"
    source: "{{ hostvars[item]['ansible_host'] }}/32"
    method: scram-sha-256
  loop: "{{ groups['mw_host'] }}"
  notify: Postgresql reloader

- name: Настроить доступ для репликации
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: host
    databases: 'replication'
    users: "{{ replica_user }}"
    source: "{{ hostvars[item]['ansible_host'] }}/32"
    method: scram-sha-256
  loop: "{{ groups['db_replica'] }}"
  notify: Postgresql reloader

- name: Установить wal_level = replica
  become: true
  become_user: postgres
  community.postgresql.postgresql_alter_system:
    param: wal_level
    value: 'replica'
  notify: Postgresql reloader

- name: Настроить прослушивание всех IP
  become: true
  become_user: postgres
  community.postgresql.postgresql_alter_system:
    param: listen_addresses
    value: '*'
  notify: Postgresql reloader

