---
# handlers file for zabbix

- name: Restart zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: true

- name: Restart zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true

- name: Restart php8.1-fpm
  ansible.builtin.service:
    name: php8.1-fpm
    state: restarted
    enabled: true
