---
# tasks file for db_host 

- name: Выполнить apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Установить пакеты
  ansible.builtin.apt:    
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Создать пользователя "{{ db_user }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE

- name: Создать пользователя "{{ replica_user }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ replica_user }}"
    password: "{{ replica_password }}"
    role_attr_flags: REPLICATION

- name: Создать базу "{{ db_name }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    state: present 

- name: Настроить доступ для хостов MediaWiki
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: host
    databases: "{{ db_name }}"
    users: "{{ db_user }}"
    source: "{{ hostvars[item]['ansible_host'] }}/32"
    method: scram-sha-256
  loop: "{{ groups['mw'] }}"
  notify: Postgresql reloader

- name: Настроить доступ для репликации
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: host
    databases: 'replication'
    users: "{{ replica_user }}"
    source: "{{ hostvars[item]['ansible_host'] }}/32"
    method: scram-sha-256
  loop: "{{ groups['db_replica'] }}"
  notify: Postgresql reloader

- name: Установить wal_level = replica
  become: true
  become_user: postgres
  community.postgresql.postgresql_alter_system:
    param: wal_level
    value: 'replica'
  notify: Postgresql reloader

- name: Настроить прослушивание всех IP
  become: true
  become_user: postgres
  community.postgresql.postgresql_alter_system:
    param: listen_addresses
    value: '*'
  notify: Postgresql reloader

- name: Создать "{{ db_backup_folder_path }}"
  ansible.builtin.file:
    path: "{{ db_backup_folder_path }}"
    state: directory
    mode: '0777'

- name: Создать "{{ backup_scripts_folder_path }}"
  ansible.builtin.file:
    path: "{{ backup_scripts_folder_path }}"
    state: directory
    mode: '0755'

- name: Создать "{{ temp_folder_path }}"
  ansible.builtin.file:
    path: "{{ temp_folder_path }}"
    state: directory
    mode: '0777'

- name: Смонтировать удаленную "{{ db_backup_folder_path }}"
  ansible.builtin.command: > 
    mount -t nfs  
      {{ hostvars['backup_server']['ansible_host'] }}:{{ db_backup_folder_path }}
      {{ db_backup_folder_path }}
  tags:
    - mount_shared

- name: Создать файл backup-скрипта
  ansible.builtin.template:
    src: "templates/{{ backup_script_name_prefix }}.j2"
    dest: "{{ backup_scripts_folder_path }}/{{ backup_script_name_prefix }}.sh"
    mode: '0755'

- name: Создать файл systemd-сервиса
  ansible.builtin.template:
    src: "templates/{{ backup_service_name_prefix }}.service.j2"
    dest: "/etc/systemd/system/{{ backup_service_name_prefix }}.service"
    owner: root
    group: root
    mode: '0644'

- name: Создать файл systemd-таймера
  ansible.builtin.template:
    src: "templates/{{ backup_service_name_prefix }}.timer.j2"
    dest: "/etc/systemd/system/{{ backup_service_name_prefix }}.timer"
    owner: root
    group: root
    mode: '0644'

- name: Перезапустить systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Запустить backup-таймер
  ansible.builtin.service:
    name: "{{ backup_service_name_prefix }}.timer"
    state: started
    enabled: true
