---
# tasks file for db_replica

- name: Выполнить apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Установить пакеты
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Запустить postgresql
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Настроить доступ для хостов MediaWiki
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: host
    databases: "{{ db_name }}"
    users: "{{ db_user }}"
    source: "{{ hostvars[item]['ansible_host'] }}/32"
    method: scram-sha-256
  loop: "{{ groups['mw'] }}"
  notify: Postgresql reloader

- name: Установить hot_standby = on
  become: true
  become_user: postgres
  community.postgresql.postgresql_alter_system:
    param: hot_standby
    value: 'on'
  notify: Postgresql reloader

- name: Остановить postgresql
  ansible.builtin.service:
    name: postgresql
    state: stopped

- name: Удалить текущие базы
  become: true
  become_user: postgres
  ansible.builtin.file:
    path: /var/lib/postgresql/14/main/
    state: absent

- name: Выполнить восстановление базы с главного сервера БД
  become: true
  become_user: postgres
  command: >
    pg_basebackup
    -h {{ hostvars['db_server']['ansible_host'] }}
    -D /var/lib/postgresql/14/main
    -U {{ replica_user }}
    -P
    -v
    -R
  environment:
    PGPASSWORD: "{{ replica_password }}"
  notify: Postgresql reloader
  tags:
    - restore_bases_for_replica
