---
# tasks file for mw_host

- name: Выполнить apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Установить пакеты
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Заменить файл конфигурации nginx
  ansible.builtin.template:
    src: nginx_default.j2
    dest: /etc/nginx/sites-enabled/default

- name: Перезапустить php8.1-fpm
  ansible.builtin.service:
    name: php8.1-fpm
    state: restarted

- name: Перезапустить nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Пинг БД
  community.postgresql.postgresql_ping:
    login_db: "{{ db_name }}"
    login_host: "{{ hostvars['db_vm']['ansible_host'] }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
  register: db_ping_result

- name: Результат проверки доступности БД
  ansible.builtin.assert:
    that: 
      - db_ping_result.is_available == true
    fail_msg: 'База данных недоступна'
    success_msg: 'ОК'

- name: Создать папку "{{ mw_site_path }}"
  ansible.builtin.file:
    path: "{{ mw_site_path }}"
    state: directory

- name: Распаковать сайт MediaWiki
  ansible.builtin.unarchive:
    src: files/mediawiki-1.42.1.tar.gz
    dest: "{{ mw_site_path }}"
    extra_opts: ['--strip-components=1']

- name: Создать папку "{{ image_folder_path }}"
  ansible.builtin.file:
    path: "{{ image_folder_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Смонтировать удаленную шару
  ansible.builtin.command: > 
    mount -t nfs  
      {{ hostvars['image_server']['ansible_host'] }}:{{ image_folder_path }}
      {{ image_folder_path }}

- name: Скопировать LocalSettings.php
  ansible.builtin.template:
    src: LocalSettings.j2
    dest: "{{ mw_site_path }}/LocalSettings.php"
    owner: www-data
    group: www-data
    mode: '0600'


