---
# tasks file for db_setup

- name: Создать пользователя "{{ db_user }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:   
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE

- name: Создать базу "{{ db_name }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"

- name: Настроить доступ для хостов MediaWiki
  become: true
  #become_user: postgre
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: host
    databases: "{{ db_name }}"
    users: "{{ db_user }}"
    source: "{{ hostvars[item]['ansible_host'] }}/32"
    method: scram-sha-256
  loop: "{{ groups['mw_host'] }}"
  notify: Postgresql reloader

- name: Настроить прослушивание всех IP
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
    state: present
  notify: Postgresql reloader
