---
# tasks file for nginxproxy

- name: Выполнить apt update
  ansible.builtin.apt:
    update_cache: true

- name: Установить пакеты
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Заменить /etc/nginx/sites-enabled/default
  ansible.builtin.template:
    src: templates/default.j2
    dest: /etc/nginx/sites-enabled/default

- name: Перезапустить nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
