mw_project:
  children:
    mw_host:
      hosts:
        mw_server_1:
          ansible_host: 10.11.0.92
          ansible_user: s14347219
          ansible_ssh_private_key_file: ./ssh_keys/s14347219-02
    db:
      hosts:
        db_vm:
          ansible_host: 10.12.0.241
          ansible_user: s14347219
          ansible_ssh_private_key_file: ./ssh_keys/s14347219-03
    db_replica:
      hosts:
        db_rep:
          ansible_host: 10.11.0.92
          ansible_user: s14347219
          ansible_ssh_private_key_file: ./ssh_keys/s14347219-02      
  vars:   
    connection_protocol: ssh
      #ansible_become: true    
      #ansible_become_user: root
    mw_site_path: '/var/www/mediawiki'
    db_name: 'my_wiki'
    db_user: 'wikiuser'
    db_password: 'wikipass'
    replica_name: 'my_wiki_replica'
    replica_user: 'wiki_replica'
    replica_password: 'wikireppass'

