---

- name: Установка Базы данных PostgreSQL
  become: true  
  hosts: db_vm
  roles:
    - db_host
  tags:
    - db_host

- name: Настройка web-серверов MediaWiki
  become: true
  hosts: mw_host
  roles:
    - mw_host
  tags:
    - mw_host

- name: Помещаем LocalSettings.php на сайт MediaWiki
  become: true
  hosts: mw_host
  roles:
    - pass_settings
  tags:
    - pass_settings

