---

- name: Установка Базы данных PostgreSQL
  become: true
  become_user: root
  hosts: db_vm
  roles:
    - db_host
  tags:
    - db_host

- name: Настройка Базы Данных PostgeSQL
  hosts: db_vm
  roles:
    - db_setup
  tags:
    - db_setup

- name: Настройка web-серверов MediaWiki
  become: true
  hosts: mw_host
  roles:
    - mw_host
  tags:
    - mw_host

