---

- name: Настройка backup-сервера
  become: true
  hosts: backup
  roles:
    - backup
  tags:
    - backup

- name: Установка Базы данных PostgreSQL
  become: true  
  hosts: db
  roles:
    - db
  tags:
    - db

- name: Настройка сервера репликации PostgreSQL
  become: true
  hosts: dbreplica
  roles:
    - dbreplica
  tags:
    - dbreplica

- name: Настройка NFS-сервера изображений
  become: true
  hosts: image
  roles:
    - image
  tags:
    - image

- name: Настройка web-серверов MediaWiki
  become: true
  hosts: mw
  roles:
    - mw
  tags:
    - mw

- name: Настройка Nginx-прокси сервера
  become: true
  hosts: nginxproxy
  roles:
    - nginxproxy
  tags:
    - nginxproxy

