---

- name: Настройка backup-сервера
  become: true
  hosts: backup_host
  roles:
    - backup_host
  tags:
    - backup_host

- name: Установка Базы данных PostgreSQL
  become: true  
  hosts: db_vm
  roles:
    - db_host
  tags:
    - db_host

- name: Настройка сервера репликации PostgreSQL
  become: true
  hosts: db_replica
  roles:
    - db_replica
  tags:
    - db_replica

- name: Настройка NFS-сервера изображений
  become: true
  hosts: image_host
  roles:
    - image_host
  tags:
    - image_host

- name: Настройка web-серверов MediaWiki
  become: true
  hosts: mw_host
  roles:
    - mw_host
  tags:
    - mw_host

