---

- name: Перевести реплику БД в режим primary
  hosts: db-replica
  tasks:
    - name: Выполнить команду pg_promote
      become: true
      become_user: postgres
      ansible.builtin.command: pg_ctlcluster 14 main promote

- name: Обновить LocalSettings.php на серверах
  hosts: mw
  become: true
  tasks:
    - name: Заменить строку с адресом БД
      ansible.builtin.lineinfile:
        path: /var/www/mediawiki/LocalSettings.php
        regexp: '^\$wgDBserver = .*;'
        line: "$wgDBserver = '{{ hostvars['dbreplica_server']['ansible_host'] }}';"

    - name: Перезапустить php8.1-fpm
      ansible.builtin.service:
        name: php8.1-fpm
        state: restarted
  tags:
    - change_LS
