---
# vars file for mw_host

packages:
  - nginx
  - php
  - php-intl
  - php-mbstring
  - php-xml
  - php-apcu
  - php-curl
  - php8.1-fpm
  - php-pgsql
  - python3-psycopg2

mw_site_path: "/var/www/mediawiki"
db_name: "my_wiki"
db_user: "wikiuser"
db_password: "wikipass"
